apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backpacking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jenia/backpacking-app-gitops
    targetRevision: HEAD
    path: base/overlays/dev/example
  destination:
    namespace: default
    destination: https://kubernetes.default.svc
