apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backpacking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jenia/backpacking-app-gitops
    targetRevision: HEAD
    path: kustomize/overlays/dev/example
    kustomize:
      version: v5.1.1
  destination:
    namespace: default
    server: https://kubernetes.default.svc
