apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  template:
    spec:
      containers:
        - name: backpacking-map
          image: eugene2022/backpacking-map:6ec5c4480b8f15e577adbfab693e1236f389e472
