apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  template:
    spec:
      containers:
        - name: backpacking-map
          image: eugene2022/backpacking-map:2bce69bb947577ef3fd519fe7be0b53d67f58921
