name: workflow_01
on:
  workflow_dispatch:
    types: [backpacking-map-docker-sha-update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        env:
          MESSAGE: ${{ github.event.client_payload.sha }}
        run: echo $MESSAGE
