name: workflow_01
on:
  repository_dispatch:
    inputs:
      sha:
        description: "sha of the backpacking map"
        required: true
        default: "00000"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: mikefarah/yq@master
      -
        name: Append backpacking-map sha tag
        env:
          MESSAGE: ${{ github.event.client_payload.sha }}
        run: |
          yq -iy '.spec.template.spec.containers[0].image += "${{ github.event.client_payload.sha }}"' kustomize/base/example/deployment.yaml
          git add kustomize/base/example/deployment.yaml
          git commit -m "Updated backpacking-map docker sha  ${{ github.event.client_payload.sha }}"
          git push
