name: workflow_01
on:
  workflow_dispatch:
    inputs:
      backpacking-map-docker-sha-update:
        description: "sha of the backpacking map"
        required: true
        default: "00000"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        env:
          MESSAGE: ${{ github.event.client_payload.sha }}
        run: echo $MESSAGE
