name: workflow_01
on:
  repository_dispatch:
    inputs:
      sha:
        description: "sha of the backpacking map"
        required: true
        default: "00000"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: mikefarah/yq@master
      -
        name: Append backpacking-map sha tag
        env:
          MESSAGE: ${{ github.event.client_payload.sha }}
        run: |
          yq -ei '.spec.template.spec.containers[0].image |= "eugene2022/backpacking-map:${{ github.event.client_payload.sha }}"' kustomize/overlays/dev/example/deployment.yaml
      -
        name: Commit files
        run: |
          git config --local user.email "jenia.ivlev@gmail.com"
          git config --local user.name "Evgeniy Ivlev"
          git add kustomize/base/example/deployment.yaml
          git commit -m "Updated backpacking-map docker sha ${{ github.event.client_payload.sha }}"
      -
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
