name: workflow_01
on:
  repository_dispatch:
    inputs:
      sha:
        description: "sha of the backpacking map"
        required: true
        default: "00000"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
        env:
          MESSAGE: ${{ github.event.client_payload.sha }}
        run: |
          echo $MESSAGE
          ls -l
